const steps=[...document.querySelectorAll("[data-step]")];let current=0;
const STORAGE_KEY="detectiveManetBar";const ids=["groupName","q1","luce","colore","pennellata","istante","proof","why","agree","different","decision","conclusion"];const $=id=>document.getElementById(id);
function save(){const d={};ids.forEach(id=>d[id]=$(id)?.value||"");localStorage.setItem(STORAGE_KEY,JSON.stringify(d));}
function selectButtons(id,v){const c=$(id);if(c)[...c.querySelectorAll("button")].forEach(b=>b.classList.toggle("selected",b.dataset.value===v));}
function load(){try{const d=JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}");ids.forEach(id=>{if($(id)&&d[id]!=null)$(id).value=d[id]});selectButtons("proofChoices",$("proof")?.value||"");selectButtons("agreeChoices",$("agree")?.value||"");if($("differentWrap"))$("differentWrap").hidden=$("agree")?.value!=="No";}catch(e){console.error(e)}}
function show(s=true){steps.forEach((x,i)=>x.hidden=i!==current);$("prev").disabled=current===0;$("next").hidden=current===steps.length-1;$("progressText").textContent=current===0?"Opera":`${current} di 5`;$("bar").style.width=`${current/5*100}%`;window.scrollTo({top:0,behavior:"smooth"});if(s)save();}
function clearErrors(){document.querySelectorAll(".errorbox").forEach(e=>e.remove());document.querySelectorAll(".invalid").forEach(e=>e.classList.remove("invalid"));}
function showError(m,es=[]){clearErrors();const b=document.createElement("div");b.className="errorbox";b.setAttribute("role","alert");b.textContent=m;steps[current].prepend(b);es.forEach(e=>e&&e.classList.add("invalid"));es.find(Boolean)?.focus?.();}
const nonEmpty=id=>(($(id)?.value||"").trim().length>0);
function validateStep(){clearErrors();if(current===0&&!nonEmpty("groupName")){showError("Inserite il nome o il codice del gruppo prima di continuare.",[$("groupName")]);return false}if(current===1&&!nonEmpty("q1")){showError("Scrivete la vostra prima osservazione prima di continuare.",[$("q1")]);return false}if(current===2){const m=["luce","colore","pennellata","istante"].filter(id=>!nonEmpty(id));if(m.length){showError("Completate tutti e quattro gli indizi prima di continuare.",m.map(id=>$(id)));return false}}if(current===3){const m=[];if(!nonEmpty("proof"))m.push($("proofChoices"));if(!nonEmpty("why"))m.push($("why"));if(m.length){showError("Scegliete l’indizio più convincente e motivate la scelta.",m);return false}}if(current===4){const m=[];if(!nonEmpty("agree"))m.push($("agreeChoices"));if($("agree")?.value==="No"&&!nonEmpty("different"))m.push($("different"));if(!nonEmpty("decision"))m.push($("decision"));if(m.length){showError("Completate il confronto del gruppo prima di continuare.",m);return false}}if(current===5&&!nonEmpty("conclusion")){showError("Scrivete la conclusione del gruppo prima di terminare.",[$("conclusion")]);return false}return true}
$("next").onclick=()=>{if(validateStep()&&current<5){current++;show()}};$("prev").onclick=()=>{if(current>0){current--;show()}};
$("proofChoices").onclick=e=>{const v=e.target.dataset.value;if(!v)return;$("proof").value=v;selectButtons("proofChoices",v);save()};
$("agreeChoices").onclick=e=>{const v=e.target.dataset.value;if(!v)return;$("agree").value=v;selectButtons("agreeChoices",v);$("differentWrap").hidden=v!=="No";if(v!=="No")$("different").value="";save()};
document.addEventListener("input",save);const dlg=$("artDialog");const openArtwork=()=>dlg?.showModal();$("openArt").onclick=openArtwork;$("artBtn").onclick=openArtwork;$("closeArt").onclick=()=>dlg?.close();
function resetActivity(){localStorage.removeItem(STORAGE_KEY);ids.forEach(id=>{if($(id))$(id).value=""});selectButtons("proofChoices","");selectButtons("agreeChoices","");$("differentWrap").hidden=true;clearErrors();current=0;show(false);localStorage.removeItem(STORAGE_KEY);}
$("sendBtn").onclick=async()=>{if(!validateStep())return;save();const endpoint=window.APP_CONFIG?.endpoint||"";if(!endpoint){$("status").textContent="Collegamento al foglio del docente non disponibile.";return}const d=JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}");d.opera="Édouard Manet – Il bar delle Folies-Bergère, 1881–1882";d.timestamp=new Date().toISOString();$("status").textContent="Invio in corso…";$("sendBtn").disabled=true;try{await fetch(endpoint,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain"},body:JSON.stringify(d)});resetActivity();$("status").textContent="Risposte inviate al docente. Il tablet è pronto per un nuovo gruppo."}catch(e){console.error(e);$("status").textContent="Invio non riuscito. Le risposte restano salvate su questo tablet."}finally{$("sendBtn").disabled=false}};
load();show();